[package]
name = "mahjong-handle-solver"
version = "0.1.0"
edition = "2024"

[dependencies]
riichi_hand = "0.6.3"
riichi = { path = "../riichi-demo" }
strum = "0.24"
strum_macros = "0.24"
indicatif = "0.17"
serde_json = "1.0"
rand = "0.8"
priority-queue = "2.2"
clap = "4.5"
csv = "1.3"